### ISSUE TITLE
Download Size?

### ISSUE THREAD

**Issue by shendrit** [joshpangell/single-use#13]
Hello everyone,
I'ts a great script, but I'm facing an issue with this script. And issue is this script doesn't show size of the file. Is it possible to show downloading size of the file while downloading a file from browser or any other program?And after one GB that is downloaded, download fails? Any answer Please.

**Comment by joshpangell** [comment]
Hello,

I updated the script to show the file size in a human readable format before download. fb4885fbac47da97550f6177ca20428cdba86a26

I additionally updated the script to tell the browser how large the payload is, so it can show appropriate download progress. 752c2c4e1ddecd499d7bd52406c70c963107f6ab

**Comment by shendrit** [comment]
I testd it. It works great to show the file size in a human readable format before download. But to tell the browser is not worknig.
