### ISSUE TITLE
.zip file download issue on Mac

### ISSUE THREAD

**Issue by chickenorbeef** [joshpangell/single-use#14]
It looks like .zip files get corrupted, at least on Mac when downloaded with Chrome.

.zip files uncompress as .cpgz files. 

Any ideas? Lots of threads on stackoverflow point to server-side script issues, but I can't seem to resolve.
Example: 
http://stackoverflow.com/questions/11495103/opening-downloaded-zip-file-creates-cpgz-file

**Comment by joshpangell** [comment]
This is the first report of this issue. There are many reasons that this could happen, aside from an actually corrupted file. It could be a server config issue, where apache is closing the download connection before the file has finished downloading. It could be a file size issue, where the size of the zip is larger than the accepted file size limit. 

Check your Apache config settings for these:
```
Upload_max_filesize
Max_input_time
Memory_limit 
Max_execution_time
Post_max_size
```

Also, in the `variables.php` file, make sure the variable 
`define('CONTENT_TYPE','application/zip');` is set correctly to be a zip.
