### ISSUE TITLE
multiple "warnings"?

### ISSUE THREAD

**Issue by CoinQ** [joshpangell/single-use#15]
Hey Josh,
sorry to bother you, this is a wonderful tool, exactly what i'm looking for, but unfortunately i'm a an absolute noob when it comes to stuff like this. it seems to bo working for everyone else, so the fault is with me, hope you got the time to take a look - i tried to follow the instructions, copied the files into a directory on my server, set permissions to 755 and tried to create a download link for the pre-existing "friday.zip" file (i didn't yet change anything in the "generate.php" nor uploaded something in the "secret" directory). i was hoping for a clean result as in your example link where it says "download key created" along with that nice clickable download link. but instead i get multiple warning messages and an unclickable link (which leads me to a "download expired" page). 

so, on the generate.php it says:
_Warning: mkdir() [function.mkdir]: Permission denied in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 32

Warning: fopen(keys/.htaccess) [function.fopen]: failed to open stream: No such file or directory in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 33

Warning: fwrite() expects parameter 1 to be resource, boolean given in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 34

Warning: fclose() expects parameter 1 to be resource, boolean given in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 35

Warning: fopen(keys/keys) [function.fopen]: failed to open stream: No such file or directory in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 41

Warning: fwrite() expects parameter 1 to be resource, boolean given in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 42

Warning: fclose() expects parameter 1 to be resource, boolean given in /www/htdocs/[myFTPlogin]/singleuse/generate.php on line 43_

.
on the download.php it says:
_Warning: file(keys/keys) [function.file]: failed to open stream: No such file or directory in /www/htdocs/[myFTPlogin]/singleuse/download.php on line 18

Warning: Invalid argument supplied for foreach() in /www/htdocs/[myFTPlogin]/singleuse/download.php on line 25

Warning: file_put_contents(keys/keys) [function.file-put-contents]: failed to open stream: No such file or directory in /www/htdocs/[myFTPlogin]/singleuse/download.php on line 35_

what am i doing wrong?

**Comment by joshpangell** [comment]
Hello there. These are all permissions issues. The `generate.php` file will create a `keys` directory in the same directory as the file itself. If that directory does not have the proper permissions, then you can not create the `keys` directory.

Based on your error logs, you have put the app here: `/www/htdocs/[myFTPlogin]/singleuse/`. You need to grant the entire `singleuse` directory + subfiles permission. If you have SSH access, you can do this by:

```
cd /www/htdocs/[myFTPlogin]
chmod 775 -R singleuse
```

If you only have FTP access, most clients will allow you to right click on a directory and set the permissions that way.
