### ISSUE TITLE
Output file is empty.

### ISSUE THREAD

**Issue by OpticDreams** [joshpangell/single-use#18]
Everything works and the file is downloaded. but upon opening it, it is empty.

**Comment by joshpangell** [comment]
Not sure on this one. I'd need to see this in action to debug. First guess would be file permissions issue, but hard to say without seeing it.

**Comment by OpticDreams** [comment]
http://www.opticdreams.com/opticstore/generate.php?1234

**Comment by OpticDreams** [comment]
the target clip is a 155 meg clip, in zip format.

**Comment by joshpangell** [comment]
The file is not being read, as noted by the `Size: 0.00`. Ensure that the `protected_path` variable in the `variables.php` file is set correctly to a actual file of the same name in the same directory. If the file does not exist, then the size can not be read.

**Comment by OpticDreams** [comment]
It was a forward slash at the beginning of the path throwing it off. 
I works fine now, thanks for your help and for for such useful script.
