### ISSUE TITLE
How to use input function in this script?

### ISSUE THREAD

**Issue by MIMAXUZ** [joshpangell/single-use#23]
Hi!
Thanks, I have one question. If I want to enter file name, file path and content type via input (HTML input form), how can I do this?

**Comment by joshpangell** [comment]
In what context? This was written with the intention of obscuring the real file path and name. 

But you could have text fields with name and then append that to the generate.php?name=file.jpg and retrieve the value inside of that file with `$name = $_GET['name']`.

Explain how you are trying to use it.
