### ISSUE TITLE
file download from cloud?

### ISSUE THREAD

**Issue by javalan** [joshpangell/single-use#27]
Hello Josh. Great work with the script!
Question: can the script be tweaked so that it downloads a file from a cloud server like DropBox, instead of a file stored locally? My server does not allow to upload files larger that 15mb, so this would be very handy. Here's a sample url to directly download a file from dropbox (sample file 6mb): https://www.dropbox.com/s/zruhvwf80c63f7i/music.mp3?dl=1

**Comment by joshpangell** [comment]
Great question. Yes, it is possible. I just updated the script to allow the possibility of a remote file to be downloaded. You can see the changes [here](https://github.com/joshpangell/single-use/commit/2b92198f62fd4ca509fb8e419207041a4e0c3259). Just use your dropbox link instead of the dummy one in the code

**Comment by javalan** [comment]
Thanks for the prompt reply, Josh. Very good news indeed! But I uploaded all the new files onto my server and ran a test. Below is the resulting message. Perhaps it has to do with the server I am using? 

Warning: fopen(https://www.dropbox.com/s/xxxxxxxxx/music.mp3?dl=1) [function.fopen]: failed to open stream: Network is unreachable in /srv/disk13/1574551/www/example.com/singleuse/download.php on line 56

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk13/1574551/www/example.com/singleuse/download.php:56) in /srv/disk13/1574551/www/example.com/singleuse/download.php on line 57

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk13/1574551/www/example.com/singleuse/download.php:56) in /srv/disk13/1574551/www/example.com/singleuse/download.php on line 58

Warning: fpassthru() expects parameter 1 to be resource, boolean given in /srv/disk13/1574551/www/example.com/singleuse/download.php on line 59

**Comment by javalan** [comment]
Ok, I tried it with a different server. IT seems to work! THanks :)

**Comment by javalan** [comment]
I tested the new code on larger media files stored in dropbox (56mb and 75mb size). The files consistently stopped downloading at about 13.5mb. I don't know the reason. In variables.php I manually specify the real size of the file. But the downloads stop at that mark. This was not an issue with smaller files.

**Comment by joshpangell** [comment]
That sounds like a server setting issue. Update the php.ini file. [Here's a StackOverflow article](https://stackoverflow.com/questions/19509440/increase-the-limit-of-file-download-size-in-document-management-system) to guide you.

**Comment by javalan** [comment]
Hi. I'm back. Had everything sorted out. The script was downloading fine on my computer and mobile phone (both using Chrome browser). However a couple of friends said they kept getting "Download expired" message when attempting to download on their browsers. One uses Firefox. I retested the script on windows IE, also OK. But on another smaller browser on my smart phone, it kept downloading a small file with the message "Download expired" :( This was the case with both local and remote files. So for some reason the script is very particular when it comes to browsers. PS. I set all files to 755 permissions.

**Comment by joshpangell** [comment]
There are a few reasons you would see that message.
1) If the download is actually expired (set by the `EXPIRATION_DATE` var in `variables.php`)
2) There is a php error when loading the download.php page (expire message is default)
3) The link did not have the key in the query string (again, expired is the default message)

Additionally, most phones don't allow the downloading of any files from a browser.
