### ISSUE TITLE
single-visit to a website

### ISSUE THREAD

**Issue by javalan** [joshpangell/single-use#28]
Hi Josh,

I was wondering whether or not the principle of a single-use download link can be applied to visiting a website. The idea is to generate a unique link, that when clicked, would direct a person to a website where he can watch a video as long as the tab is open. The "real" url of the website is "somehow" masked by the unique link. If that link is saved and reused (or the site is refreshed), the person would be presented with an expired message. Is this possible?

**Comment by joshpangell** [comment]
That is a pretty interesting idea, but not what this software does. 

Some advice on your quest:
You'd be unable to make randomized different domains without actually buying domains. However, you could have a randomized subdomain, like random1234.domain.com. Or you could also have random url paths, like domain.com/random5678.

Regarding a video — if your browser can view it, then it has been downloaded. Unless you do some fancy streaming (like Netflix, Youtube, Vimeo, etc), the video will be downloaded to the computer of the viewer and could be watched again.
