### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by gat0s** [joshpangell/single-use#29]
Hi!
The key is written, and the rest of generate.php loads, but no links. Any guess on what I'm doing wrong?
THANKS!

```						<h6>Your new single-use download links:<h6><br>
			<? foreach ($download_list as $download) { ?>			
			<h4>
				<a href=""></a><br>
				Size: 			</h4>
			<? } ?>
			
			<br><br>
			<a href="/singleuse">Back to the demo</a>

**Comment by joshpangell** [comment]
It looks like you removed the code that creates the link. See the demo here https://github.com/joshpangell/single-use/blob/master/generate.php#L81

**Comment by gat0s** [comment]
Hi. Thanks for responding.
That's _view source_ of the page as it loads. Gernerate.php is unchanged from the demo configuration.

```			<h6>Your new single-use download links:<h6><br>
					
			<h4>
				<a href="<?= $download['download_link'] ?>"><?= $download['download_link'] ?></a><br>
				Size: <?= $download['filesize'] ?>
			</h4>
			<? } ?>
			
			<br><br>
			<a href="/singleuse">Back to the demo</a>

**Comment by joshpangell** [comment]
I see. That would indicate that your server is not running, or executing, php.

**Comment by gat0s** [comment]
It is though, right, because it's displaying the php pages and creating the keys?

**Comment by gat0s** [comment]
System | Linu xxxx SMP Mon Jan 15 23:35:15 UTC 2018 x86_64
-- | --
Build Date | Dec 14 2017 20:50:33
Server API | Apache 2.0 Handler
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc
Loaded Configuration File | /etc/php.ini
Scan this dir for additional .ini files | /etc/php.d
Additional .ini files parsed | /etc/php.d/curl.ini, /etc/php.d/fileinfo.ini, /etc/php.d/json.ini, /etc/php.d/mysqlnd.ini, /etc/php.d/mysqlnd_mysql.ini, /etc/php.d/mysqlnd_mysqli.ini, /etc/php.d/pdo.ini, /etc/php.d/pdo_mysqlnd.ini, /etc/php.d/pdo_sqlite.ini, /etc/php.d/phar.ini, /etc/php.d/sqlite3.ini, /etc/php.d/zip.ini
PHP API | 20100412
PHP Extension | 20100525
Zend Extension | 220100525
Zend Extension Build | API220100525,NTS
PHP Extension Build | API20100525,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | disabled
Zend Memory Manager | enabled
Zend Multibyte Support | disabled
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, sslv3, tls
Registered Stream Filters | zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

**Comment by cfishwick** [comment]
I had this exact same problem, had to modify the code in generate.php slightly to make it work.
Original:

    <? for each ($download_list as $download) { ?>			
    <h4>
	    	<a href="<?= $download['download_link'] ?>"><?= $download['download_link'] ?></a><br>
	    	Size: <?= $download['filesize'] ?>
      </h4>
    <? } ?>

My update:

    <?php for each ($download_list as $download) { ?>
      <h4>
	    	<a href="<?= $download['download_link'] ?>"><?= $download['download_link'] ?></a><br>
	    	Size: <?= $download['filesize'] ?>
      </h4>
    <?php } ?>

Note the addition of the "php" tag on the first and last line.

**Comment by gat0s** [comment]
Thanks for posting, @cfishwick! I didn't need the array, but ultimately ended up with a similar solution and just cut to the chase:
`<?php echo "https://" . $_SERVER['HTTP_HOST'] . DOWNLOAD_PATH . "?key=" . $new . "&i=" . $key; ?>">`
