### ISSUE TITLE
Size Limit?

### ISSUE THREAD

**Issue by phantomflanflinger** [joshpangell/single-use#30]
Works great, but I just tried to use it on my server with a 70MB file and I got a 404 error. Fine with smaller files.

OK so this may be my server's problem, but if so I can't work out what it is - any idea?

Thanks, 

PFF

**Comment by joshpangell** [comment]
Hello,

This is very similar to [this issue](https://github.com/joshpangell/single-use/issues/22) as well as [this issue](https://github.com/joshpangell/single-use/issues/17). Hopefully one of those two should work for you.

**Comment by joshpangell** [comment]
No problem, glad that worked for you.
