### ISSUE TITLE
I only get a text saying "Size:" and nothing else

### ISSUE THREAD

**Issue by imusingastockdell** [joshpangell/single-use#31]
![capture](https://user-images.githubusercontent.com/25141325/47590414-edffb180-d9b7-11e8-8cff-30d4c96bac2d.PNG)

**Comment by rafaeloros** [comment]
In generate.php replace
			<? foreach ($download_list as $download) { ?>			
			<h4>
				<a href="<?= $download['download_link'] ?>"><?= $download['download_link'] ?></a><br>
				Size: <?= $download['filesize'] ?>
			</h4>
			<? } ?>
with 
			<?php foreach ($download_list as $download) { ?>			
			<h4>
				<a href="<?= $download['download_link'] ?>"><?= $download['download_link'] ?></a><br>
				Size: <?= $download['filesize'] ?>
			</h4>
			<?php } ?>

it did the trick for me

**Comment by imusingastockdell** [comment]
I tested it and it works now! Thanks.
