### ISSUE TITLE
Single-use issue

### ISSUE THREAD

**Issue by lampatt** [joshpangell/single-use#32]
l have been try the script but l get the following error message, am new to programming and want to use this script in my project. Any help?

Download key created
YOUR NEW SINGLE-USE DOWNLOAD LINKS:

Notice: Undefined index: download_link in C:\xampp\htdocs\singleuse\generate.php on line 83

Size: 
Notice: Undefined index: filesize in C:\xampp\htdocs\singleuse\generate.php on line 84

**Comment by joshpangell** [comment]
A `Notice` is not an error. That is telling you that the key of `download_lnik` in the array `$download` is not found on line 83 here: `$download['download_link']`.

What this likely means is that this value was never set on line 34 like it was supposed to, which probably means that the values inside of `variables.php` for `$PROTECTED_DOWNLOADS` were either never set, or they are not being read. 

Finally, it looks like you're running this for xampp on a Windows machine. This script has never been tested on Windows, so I can't guarantee that it will work. It was written to run on Linux.

**Comment by lampatt** [comment]
Thank you very much Josh for your prompt response and help. Really appreciate it.

Do you please have one that can run on windows?

Please advise.

Thank you,

Patrick
________________________________

**Comment by lampatt** [comment]
Thanks Josh for your prompt response l really appreciate. Please forgive me l am now learning programming.

It is now working on a live server. But l get the feed back:File not found.
though there are two file1 and file2 in the secret folder. Please advise

secondly, l wish to apply this system to my project such that after payment is done, the link to download the particular mp3 file that was purchased can be sent to the buyer's email so after clicking on the link can download only that particular mp3 file. Can you please help with that?

l really love your tutorials and wish to learn more from you. Please keep up the good work. God bless you.

Patrick
________________________________
