### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by devaunmp** [joshpangell/single-use#6]
Hello! I believe I followed your direction exact but for whatever reason the page doesnt generate clickable hyperlinks, just text. This the page I've created http://jameswf.com/download/generate.php?1234 Can you please help? Thank You in advance!

**Comment by xprox** [comment]
Hi, I have implemented  all your steps and it's working great
But I need to make the generated link open directly in new window tab without clicking it 
Waiting your soonest reply
Thanks in advance

**Comment by joshpangell** [comment]
Just like any other anchor tag, you can use the [target](http://www.w3schools.com/tags/att_a_target.asp) attribute to specify new window. In your case, you'd want `target="_blank"`.

**Comment by xprox** [comment]
I tried that but it wasn't work,, I think I made something wrong, here what I used:
  <nl><a href="<?= "http://" . $_SERVER['HTTP_HOST'] . DOWNLOAD_PATH . "?" . $new; ?> "target="_self"></a></nl>

I appreciate if you can clarify
As I need when I put the url/generate.php?123 in browser
its convert me directly to the generated link to download the file  ----> url/download.php?key************
to open it in same frame
Regards
