### ISSUE TITLE
Multiple Admins and automaticaly deleting of Admins/users?

### ISSUE THREAD

**Issue by scalpmonkey** [joshpangell/single-use#9]
Hi,
Since there was no request tab I write this here ;D

The ultimate combo for this already great script would be possibility that the admins are pulled from some file on the server and even the possibility to delete the user after downloading the file or may be certain number of downloads.

Thanks,
S@

**Comment by kohbo** [comment]
I'm thinking of contributing to this project and having trouble picturing what the multiple admins could be used for. The admin string is just used for simple authentication at this point. Do you mean the admin variable/key would change every time a link is generated as well?

The multiple downloads option is a possibility for users wanting more advanced features.
